//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 tool_character.rc 使用
//
#define IDD_DLG_SLIDER_VIEW             9
#define IDD_ABOUTBOX                    100
#define IDR_HTML_DLGLINK                103
#define IDR_MAINFRAME                   128
#define IDR_tool_characterTYPE          129
#define ID_VIEW_BRUSH_PROPERTY          129
#define ID_VIEW_TREE_VIEW               129
#define ID_VIEW_BRUSH_MAP               130
#define ID_TREE_OBJ_VIEW                130
#define ID_VIEW_BRUSH_OBJECT            131
#define ID_VIEW_PROPERTY_VIEW           131
#define IDD_DIALOG_NEW_SHADER           131
#define ID_VIEW_BRUSH_VERTEX            132
#define ID_VIEW_SLIDER_VIEW             132
#define IDB_BITMAP_BRUSH_OBJECT         132
#define IDB_TREE_VIEW_OBJECT            132
#define IDD_LINK                        132
#define ID_VIEW_BRUSH_COLOR             133
#define IDS_GRID_DIR_LIGHT              133
#define IDD_MERGE_ACTOR                 133
#define IDS_GRID_SHADER_NAME            134
#define IDD_DIALOG_POSE                 134
#define ID_VIEW_PROPERTY_SHADER         135
#define IDD_DIALOG_POSE_CONN            135
#define ID_SHADER_VIEW                  136
#define IDD_DIALOG_NEW_EFFECT           136
#define ID_CG_SHADER_LIST               137
#define ID_BASE_SHADER_LIST             137
#define IDR_MENU_POP                    137
#define IDR_TOOLBAR_TOOLS               138
#define ID_VIEW_PROPERTY_SHADER_KEY     138
#define IDD_DIALOG_VER_FIX              138
#define ID_ADD_SHADER_KEYFRAME          139
#define IDD_DLG_CHANNEL_INFO            139
#define ID_DEL_KEYFRAME                 140
#define IDD_DLG_KEY_INFO                140
#define ID_VIEW_PROPERTY_POSE           141
#define IDD_DIALOG                      141
#define IDD_DLG_GET_BONE                141
#define ID_EFFECT_SHADER_LIST           142
#define IDD_DIALOG_CREATE_FF            142
#define ID_ADD_EFFECT_SHADER            143
#define IDD_DIALOG_RELATED_ACTOR        143
#define ID_GRID_SHADER                  144
#define IDD_MERGE_ACTOR_NEW             144
#define ID_GRID_SHADER_KEY              145
#define IDD_MERGE_ACTOR1                145
#define ID_SHADER_LIST                  146
#define ID_GRID_OBJECT                  147
#define ID_GRID_POSE                    148
#define ID_SKIN_LIST                    149
#define ID_GRID_EFFECT                  150
#define ID_VIEW_PROPERTY_EFFECT         151
#define ID_VIEW_TIME                    152
#define ID_GRID_ENV                     153
#define ID_GRID_ACTOR                   154
#define ID_GRID_MTLLIB                  155
#define ID_VIEW_MTL                     156
#define ID_VIEW_EFT                     157
#define ID_CHANNEL_INFO                 158
#define ID_KEY_INFO                     159
#define ID_VIEW_KEY                     160
#define ID_GRID_CHANNEL_PROP            161
#define ID_GET_RELATED_RES              162
#define ID_GRID_LINKBOX                 163
#define IDC_SLIDER1                     1000
#define IDC_ANIM_SLIDER                 1000
#define IDC_EDIT1                       1001
#define IDC_FRAME_INFO                  1001
#define IDC_CREATE_ES_ADD               1001
#define IDC_ACTOR1                      1001
#define IDC_FILE                        1001
#define IDC_MSG                         1001
#define IDC_EDIT2                       1002
#define IDC_PATH                        1002
#define IDC_ACTOR2                      1002
#define IDC_EDIT_EVENT_PARAM            1002
#define IDC_BUTTON1                     1003
#define IDC_ANIM_PLAY                   1003
#define IDC_GET_FILE_NAME               1003
#define IDC_LOAD_WEAPON                 1003
#define IDC_GET_ACTOR1                  1003
#define IDC_BUTTON_ADD_EVENT            1003
#define IDC_CREATE_EMITTER              1003
#define IDC_START                       1003
#define IDC_BUTTON_READD                1003
#define IDC_BUTTON_ADD                  1003
#define IDC_BUTTON2                     1004
#define IDC_ANIM_STOP                   1004
#define IDC_CREATE_SHADER_ADD           1004
#define IDC_CREATE_ES_ADD2              1004
#define IDC_CREATE_ES_BLEND             1004
#define IDC_GET_ACTOR2                  1004
#define IDC_BUTTON_DEL_EVENT            1004
#define IDC_CREATE_RIBBON               1004
#define IDC_BUTTON_CLR                  1004
#define IDC_CREATE_RIBBON2              1005
#define IDC_CREATE_GLOW                 1005
#define IDC_GET_ACTOR3                  1005
#define IDC_ACTOR_DST                   1005
#define IDC_EDIT_EVENT_PARAM_1          1005
#define IDC_COMBO1                      1006
#define IDC_REPLACE                     1006
#define IDC_CREATE_ES_BLEND2            1007
#define IDC_CREATE_ES_CY                1007
#define IDC_BUTTON3                     1008
#define IDC_CREATE_BS_3D                1008
#define IDC_DEL_WEAPON                  1008
#define IDC_BUTTON_UPDATE               1008
#define IDC_POSE_CONN                   1008
#define IDC_CREATE_STANDARD             1008
#define IDC_EDIT_EVENT_PARAM_2          1010
#define IDC_ANIM_LOOP                   1011
#define IDC_LIST1                       1012
#define IDC_OB_LIST                     1012
#define IDC_WEAPON_SLOT                 1012
#define IDC_LIST_EVENT                  1012
#define IDC_LIST_POSE1                  1012
#define IDC_BONE_LIST                   1012
#define IDC_LIST_ACTOR                  1012
#define IDC_PET_SLOT                    1013
#define IDC_BUTTON_DEL_EVENT2           1013
#define IDC_POSE                        1014
#define IDC_CHECK1                      1015
#define IDC_EDIT_EVENT_ACTION           1016
#define IDC_LIST2                       1017
#define IDC_LIST_POSE2                  1017
#define IDC_EDIT_KEY_FRAME              1017
#define IDC_CREATE                      1026
#define IDC_COMBO2                      1027
#define IDC_NAME                        1028
#define IDC_LIST                        1029
#define IDC_PROGRESS                    1030
#define IDC_STATIC_0                    1031
#define IDC_STATIC_1                    1032
#define IDC_STATIC_2                    1033
#define IDC_BUTTON_F0                   1035
#define ID_32771                        32771
#define ID_BUTTON32783                  32783
#define ID_BUTTON32784                  32784
#define ID_NEW_SHADER                   32786
#define ID_OPEN_SKECHAR                 32791
#define ID_OPEN_SKESKIN                 32792
#define ID_SAVE_SKECHAR                 32795
#define ID_SAVE_SKESKIN                 32797
#define ID_LINK                         32799
#define ID_SAVE_AS_ACTOR                32800
#define ID_OPEN_ACTOR                   32803
#define ID_32804                        32804
#define ID_SAVE_AS_SKIN                 32806
#define ID_SAVE_ALL                     32807
#define ID_MERGE_ACTOR                  32809
#define ID_NEW_EFFECT                   32811
#define ID_TEST1                        32812
#define ID_TEST1_TEST333                32815
#define ID_VER_FIX                      32817
#define ID_TEST1_DELCHANNEL             32818
#define ID_LOCK_CHANNEL                 32820
#define ID_CHANGE_GRIDSIZE              32822
#define ID_MODIFY_CHANNEL               32824
#define ID_ADD_KEY                      32825
#define ID_DEL_KEY                      32826
#define ID_MODIFY_KEY                   32828
#define ID_SAVE_AS_MTLLIB               32829
#define ID_SAVE_AS_EFFECT               32830
#define ID_CON_PAN                      32831
#define ID_BUTTON32834                  32834
#define ID_OPEN_RELATED                 32836
#define ID_MODIFY_RELATED_ACTOR         32839
#define IDC_POSE_LIST                   32840
#define ID_COPY_EFFECT                  32843
#define ID_BUTTON32844                  32844
#define IDC_MESH_VIEW                   32844
#define IDC_PAPAMIETER                  32845
#define IDC_PARAMETER                   32845
#define ID_TEST2                        32846
#define ID_SHOWLINK                     32849
#define IDC_SHOWLINK                    32850

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32851
#define _APS_NEXT_CONTROL_VALUE         1036
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
